In [48]:
import sys
sys.path.insert(0, '/Users/niyi/Documents/GitHub/Optimal-Control/Tools')
from ActorCriticNetworks import ActorNetwork, CriticNetwork
import torch as T
import torch.nn as nn 

In [49]:
N= CriticNetwork(5, 2, (10, 15), (nn.ReLU(), nn.ReLU()), name='tb', learning_rate=0.02)

bt= T.tensor([[-1.4355, -0.7806,  0.3042,  1.1601, -0.1184]])
at= T.tensor([[0.8233, 0.8126]])
for target_param in N.parameters():
    print(target_param)
bt, at, N(bt, at)

Parameter containing:
tensor([-0.1565, -0.2893, -0.1337,  0.3331,  0.0617, -0.2237,  0.2656, -0.1576,
         0.3041, -0.2296], requires_grad=True)
Parameter containing:
tensor([[0.6255],
        [0.5450],
        [0.4521],
        [0.6191],
        [0.5168],
        [0.5813],
        [0.6737],
        [0.6560],
        [0.5755],
        [0.5931]], requires_grad=True)
Parameter containing:
tensor([[ 0.2235, -0.3209, -0.1716,  0.2984, -0.1159, -0.2993, -0.1299],
        [ 0.1776,  0.3603, -0.1038,  0.0690, -0.0924,  0.0322,  0.3324],
        [ 0.0772, -0.2427, -0.3090,  0.1524,  0.0741,  0.0567, -0.1101],
        [-0.2432, -0.3301, -0.2396, -0.3144, -0.1061,  0.1839, -0.1174],
        [ 0.1448, -0.0919,  0.0917, -0.1863, -0.0338, -0.3037, -0.3181],
        [ 0.2559, -0.2742, -0.3169,  0.1327,  0.0681,  0.0542,  0.2677],
        [ 0.3460, -0.1379, -0.2926,  0.2752,  0.2115,  0.2392,  0.2277],
        [-0.2035,  0.1539, -0.3403, -0.1518, -0.0531, -0.2973,  0.3677],
        [ 0.3680,  0.1

(tensor([[-1.4355, -0.7806,  0.3042,  1.1601, -0.1184]]),
 tensor([[0.8233, 0.8126]]),
 tensor([[0.2157]], grad_fn=<AddmmBackward0>))

In [50]:
Nt= ActorNetwork(0.02, 5, 10, 15, 2, name='btt')

btt= T.tensor([[-0.6552,  0.0852,  2.0087, -0.6352,  0.4445]])
att= T.randn(1, 2)

# Nt.load_checkpoint()
btt, Nt(btt)

(tensor([[-0.6552,  0.0852,  2.0087, -0.6352,  0.4445]]),
 tensor([[-0.3505,  0.0238]], grad_fn=<AddmmBackward0>))