In [22]:
import sys
sys.path.insert(0, '/Users/niyi/Documents/GitHub/Optimal-Control/Tools')
from ActorCriticNetworks import ActorNetwork, CriticNetwork
import torch as T
import torch.nn as nn 

In [23]:
N= CriticNetwork(5, 2, (10, 15), (nn.ReLU(), nn.ReLU()), name='tb', learning_rate=0.02)

bt= T.tensor([[-1.4355, -0.7806,  0.3042,  1.1601, -0.1184]])
at= T.tensor([[0.8233, 0.8126]])
for target_param in N.parameters():
    print(target_param)
bt, at, N(bt, at)

Parameter containing:
tensor([-0.2706, -0.0614, -0.2883,  0.2431,  0.3263, -0.0296,  0.3737, -0.2038,
        -0.0088,  0.2855], requires_grad=True)
Parameter containing:
tensor([[0.5295],
        [0.7208],
        [0.4848],
        [0.5669],
        [0.7163],
        [0.5158],
        [0.4331],
        [0.6241],
        [0.5239],
        [0.5695]], requires_grad=True)
Parameter containing:
tensor([[ 0.3007,  0.1331, -0.1733,  0.3065,  0.0327,  0.0237, -0.2158],
        [ 0.2032, -0.2366,  0.3346,  0.2217,  0.3775, -0.1301,  0.3189],
        [-0.0928,  0.3732,  0.1267,  0.1218,  0.1164, -0.0750, -0.1924],
        [ 0.2861,  0.2474,  0.2067, -0.0808, -0.3582,  0.0027, -0.0285],
        [-0.2669, -0.1725,  0.2255,  0.1891,  0.2597, -0.3458,  0.3720],
        [-0.1186,  0.3734, -0.0652, -0.1471, -0.0090, -0.2521, -0.1517],
        [ 0.1143,  0.2857,  0.1075, -0.2654,  0.0885,  0.0315,  0.0458],
        [-0.2741,  0.1005, -0.2027, -0.3302, -0.2264,  0.1264, -0.2949],
        [-0.1325,  0.2

(tensor([[-1.4355, -0.7806,  0.3042,  1.1601, -0.1184]]),
 tensor([[0.8233, 0.8126]]),
 tensor([[-0.2387]], grad_fn=<AddmmBackward0>))

In [24]:
Nt= ActorNetwork(5, 2, (10, 15), (nn.ReLU(), nn.ReLU()), learning_rate=0.02, name='btt')

btt= T.tensor([[-0.6552,  0.0852,  2.0087, -0.6352,  0.4445]])
att= T.randn(1, 2)

# Nt.load_checkpoint()
btt, Nt(btt)

TypeError: ActorNetwork.__init__() got multiple values for argument 'name'